
# Hacer todos los programas
all : filtroProc filtroHilos

# Compilar filtroProc
filtroProc : 	filtroProc.c
		gcc filtroProc.c -o filtroProc

# Compilar filtroHilos
filtroHilos : 	filtroHilos.c
		gcc filtroHilos.c -lpthread -o filtroHilos
