/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _TIEMPO_H_RPCGEN
#define _TIEMPO_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


#define PROGRAMA_TIEMPO 0x20038207
#define VERSION_TIEMPO 1

#if defined(__STDC__) || defined(__cplusplus)
#define peticion_hora 1
extern  double * peticion_hora_1(void *, CLIENT *);
extern  double * peticion_hora_1_svc(void *, struct svc_req *);
#define peticion_calidad 2
extern  int * peticion_calidad_1(void *, CLIENT *);
extern  int * peticion_calidad_1_svc(void *, struct svc_req *);
extern int programa_tiempo_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define peticion_hora 1
extern  double * peticion_hora_1();
extern  double * peticion_hora_1_svc();
#define peticion_calidad 2
extern  int * peticion_calidad_1();
extern  int * peticion_calidad_1_svc();
extern int programa_tiempo_1_freeresult ();
#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_TIEMPO_H_RPCGEN */
